server:
  http_listen_port: 3100
  http_server_read_timeout: 120s
  http_server_write_timeout: 120s

auth_enabled: false

common:
  path_prefix: /data/loki-logs
  storage:
    s3:
      bucketnames: ${LOKI_S3_BUCKET}         
      endpoint: ${S3_ENDPOINT}            
      region: ${LOKI_AWS_REGION}
      s3forcepathstyle: ${S3_FORCE_PATH_STYLE:true}
      insecure: false
  replication_factor: 1                       
  ring:
    kvstore:
      store: inmemory                         

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/boltdb-cache
    shared_store: s3

compactor:
  working_directory: /data/loki/compactor
  shared_store: s3
  compaction_interval: 5m
  retention_enabled: true

limits_config:
  max_global_streams_per_user: 100000
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  reject_old_samples: true
  reject_old_samples_max_age: 168h      # reject >7d-old
  retention_period: 720h                # 30 days global retention (tune per tenant if needed)
  allow_structured_metadata: true

ruler:
  storage:
    type: s3
    s3:
      bucketnames: ${LOKI_S3_BUCKET}
      region: ${LOKI_AWS_REGION}
  rule_path: /data/loki/rules
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true

frontend:
  # optional, improves query performance
  log_queries_longer_than: 10s

querier:
  max_concurrent: 8

query_range:
  align_queries_with_step: true
  max_retries: 5

analytics:
  reporting_enabled: false
