apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromium-renderer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chromium-renderer
  template:
    metadata:
      labels:
        app: chromium-renderer
    spec:
      serviceAccountName: taskforge-sa
      containers:
        - name: chromium-renderer
          image: chromium-renderer:dev
          ports:
            - containerPort: 3000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: taskforge-secrets
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: taskforge-secrets
            - name: S3_BUCKET_NAME
              valueFrom: 
                secretKeyRef:
                  key: S3_BUCKET_NAME
                  name: taskforge-secrets
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: AWS_REGION
                  name: taskforge-secrets
            - name: RENDER_TOKEN
              valueFrom: 
                secretKeyRef:
                  key: CHROMIUM_RENDERER_TOKEN
                  name: taskforge-secrets
            - name: PORT
              value: "3000"
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 18
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 15
            failureThreshold: 5
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

