apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'severity', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - match:
            severity: critical
          receiver: slack-critical
          group_wait: 0s
          repeat_interval: 1h
        - match:
            severity: warning
          receiver: slack-warning
          group_wait: 2m
          repeat_interval: 6h
        - match:
            severity: info
          receiver: slack-info
          group_wait: 5m
          repeat_interval: 12h
      receiver: slack-default

    receivers:
      - name: slack-critical
        slack_configs:
          - send_resolved: true
            channel: '#critical-alerts'
            username: 'AlertManager'
            api_url: '${SLACK_WEBHOOK_URL}'
            title: '🚨 CRITICAL: {{ .CommonAnnotations.summary }}'
            text: '{{ .CommonAnnotations.description }}'

      - name: slack-warning
        slack_configs:
          - send_resolved: true
            channel: '#warnings'
            username: 'AlertManager'
            api_url: '${SLACK_WEBHOOK_URL}'
            title: '⚠️ WARNING: {{ .CommonAnnotations.summary }}'
            text: '{{ .CommonAnnotations.description }}'

      - name: slack-info
        slack_configs:
          - send_resolved: true
            channel: '#info'
            username: 'AlertManager'
            api_url: '${SLACK_WEBHOOK_URL}'
            title: 'ℹ️ INFO: {{ .CommonAnnotations.summary }}'
            text: '{{ .CommonAnnotations.description }}'

      - name: slack-default
        slack_configs:
          - send_resolved: true
            channel: '#alerts'
            username: 'AlertManager'
            api_url: '${SLACK_WEBHOOK_URL}'
            title: '{{ .CommonAnnotations.summary }}'
            text: '{{ .CommonAnnotations.description }}'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      initContainers:
        - name: config-replacer
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              cp /tmp/alertmanager-template/alertmanager.yml /tmp/alertmanager-config/alertmanager.yml
              sed -i "s|\${SLACK_WEBHOOK_URL}|${SLACK_WEBHOOK_URL}|g" /tmp/alertmanager-config/alertmanager.yml
          env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: alertmanager-secrets
                  key: SLACK_WEBHOOK_URL
          volumeMounts:
            - name: alertmanager-config-template
              mountPath: /tmp/alertmanager-template
            - name: alertmanager-config-processed
              mountPath: /tmp/alertmanager-config
      containers:
        - name: alertmanager
          image: prom/alertmanager:latest
          ports:
            - containerPort: 9093
          args:
            - '--config.file=/etc/alertmanager/alertmanager.yml'
            - '--storage.path=/alertmanager'
          volumeMounts:
            - name: alertmanager-config-processed
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
            - name: alertmanager-storage
              mountPath: /alertmanager
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: alertmanager-config-template
          configMap:
            name: alertmanager-config
        - name: alertmanager-config-processed
          emptyDir: {}
        - name: alertmanager-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
  type: ClusterIP