apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-simple-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'severity', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'null'

    receivers:
      - name: 'null'