apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - secrets.yaml
  - prometheus.yaml
  - grafana.yaml
  - alertmanager.yaml
  - loki.yaml
  - promtail.yaml
  - ingress.yaml
