apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki-config.yml: |
    server:
      http_listen_port: 3100
      http_server_read_timeout: 120s
      http_server_write_timeout: 120s

    auth_enabled: false

    common:
      path_prefix: /data/loki-logs
      storage:
        s3:
          bucketnames: ${LOKI_S3_BUCKET}         
          endpoint: ${S3_ENDPOINT}            
          region: ${LOKI_AWS_REGION}
          s3forcepathstyle: ${S3_FORCE_PATH_STYLE:true}
          insecure: false
      replication_factor: 1                       
      ring:
        kvstore:
          store: inmemory                         

    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/boltdb-cache
        shared_store: s3

    compactor:
      working_directory: /data/loki/compactor
      shared_store: s3
      compaction_interval: 5m
      retention_enabled: true

    limits_config:
      max_global_streams_per_user: 100000
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 32
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 720h
      allow_structured_metadata: true

    ruler:
      storage:
        type: s3
        s3:
          bucketnames: ${LOKI_S3_BUCKET}
          region: ${LOKI_AWS_REGION}
      rule_path: /data/loki/rules
      alertmanager_url: http://alertmanager.monitoring.svc.cluster.local:9093
      ring:
        kvstore:
          store: inmemory
      enable_api: true

    frontend:
      log_queries_longer_than: 10s

    querier:
      max_concurrent: 8

    query_range:
      align_queries_with_step: true
      max_retries: 5

    analytics:
      reporting_enabled: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.8
          ports:
            - containerPort: 3100
          args:
            - "-config.file=/etc/loki/config.yml"
            - "-config.expand-env=true"
          env:
            # Standard AWS environment variables for SDK
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: LOKI_AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: LOKI_AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: LOKI_AWS_REGION
            # Custom variables for Loki config expansion
            - name: LOKI_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: LOKI_AWS_ACCESS_KEY_ID
            - name: LOKI_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: LOKI_AWS_SECRET_ACCESS_KEY
            - name: LOKI_AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: LOKI_AWS_REGION
            - name: LOKI_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: LOKI_S3_BUCKET
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: S3_ENDPOINT
            - name: S3_FORCE_PATH_STYLE
              value: "true"
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/config.yml
              subPath: loki-config.yml
            - name: loki-data
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
  type: ClusterIP