apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 5000
      derivedFields:
        # Example: click a traceId value in logs to open tracing (Tempo/Jaeger) later
        - name: traceId
          matcherRegex: "(?:traceId|trace_id)=(\\w+)"
          url: ""
