apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-node-prod

resources:
  - ./gateway-node-ingress.yaml

# patches:
#   - target:
#       kind: Ingress
#       name: gateway-node-ingress
#     patch: |-
#       - op: replace
#         path: /spec/rules/0/host
#         value: api-taskforge.oviecodes.xyz
#       - op: add
#         path: /spec/tls
#           value:
#             - hosts:
#                 - api-taskforge.oviecodes.xyz
#               secretName: api-taskforge-tls
  # - target:
  #     kind: Ingress
  #     name: status-gateway-ingress
  #   patch: |-
  #     - op: replace
  #       path: /spec/rules/0/host
  #       value: status-taskforge.oviecode.xyz
#      - op: add
#        path: /spec/tls
        # value:
        #   - hosts:
        #       - status.taskforge.com
        #     secretName: socket-taskforge-tls

