global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - match:
        severity: critical
      receiver: slack-critical
      group_wait: 0s
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: slack-warning
      group_wait: 2m
      repeat_interval: 6h
    - match:
        severity: info
      receiver: slack-info
      group_wait: 5m
      repeat_interval: 12h
  receiver: slack-default

receivers:
  - name: slack-critical
    slack_configs:
      - send_resolved: true
        channel: '#critical-alerts'
        username: 'AlertManager'
        api_url: '${SLACK_WEBHOOK_URL}'
        title: '🚨 CRITICAL: {{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'

  - name: slack-warning
    slack_configs:
      - send_resolved: true
        channel: '#warnings'
        username: 'AlertManager'
        api_url: '${SLACK_WEBHOOK_URL}'
        title: '⚠️ WARNING: {{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'

  - name: slack-info
    slack_configs:
      - send_resolved: true
        channel: '#info'
        username: 'AlertManager'
        api_url: '${SLACK_WEBHOOK_URL}'
        title: 'ℹ️ INFO: {{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'

  - name: slack-default
    slack_configs:
      - send_resolved: true
        channel: '#alerts'
        username: 'AlertManager'
        api_url: '${SLACK_WEBHOOK_URL}'
        title: '{{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'
