# gateway-node-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-node
  namespace: taskforge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-node
  template:
    metadata:
      labels:
        app: gateway-node
    spec:
      serviceAccountName: taskforge-sa
      containers:
        - name: gateway-node
          image: gateway-node:dev
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: taskforge-secrets, key: POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: taskforge-secrets, key: POSTGRES_PASSWORD } }
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres.taskforge.svc.cluster.local:5432"
            - name: REDIS_PASSWORD
              valueFrom: { secretKeyRef: { name: taskforge-secrets, key: REDIS_PASSWORD } }
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@redis.taskforge.svc.cluster.local:6379"
            - name: JWT_SECRET
              valueFrom: { secretKeyRef: { name: taskforge-secrets, key: JWT_SECRET } }
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "development"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
          readinessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet: { path: /health/live, port: 3000 }
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

---
# Main service
apiVersion: v1
kind: Service
metadata:
  name: gateway-node
  namespace: taskforge
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: gateway-node
  type: NodePort




