# outbox-publisher-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outbox-publisher
  namespace: taskforge
spec:
  replicas: 1   # usually runs single instance to avoid double-publishing
  selector:
    matchLabels:
      app: outbox-publisher
  template:
    metadata:
      labels:
        app: outbox-publisher
    spec:
      serviceAccountName: taskforge-sa
      containers:
        - name: outbox-publisher
          image: outbox-publisher:dev
          ports:
            - containerPort: 8200
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: taskforge-secrets, key: POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: taskforge-secrets, key: POSTGRES_PASSWORD } }
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres.taskforge.svc.cluster.local:5432"
            - name: RABBITMQ_USER
              valueFrom: { secretKeyRef: { name: taskforge-secrets, key: RABBITMQ_USER } }
            - name: RABBITMQ_PASSWORD
              valueFrom: { secretKeyRef: { name: taskforge-secrets, key: RABBITMQ_PASSWORD } }
            - name: RABBITMQ_URL
              value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq.taskforge.svc.cluster.local:5672
            - name: EXCHANGE_NAME
              value: "task.exchange"
            - name: OUTBOX_POLL_INTERVAL
              value: "5000"
            - name: HEALTH_PORT
              value: "8200"
            - name: NODE_ENV
              value: "development"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
          readinessProbe:
            httpGet: { path: /health, port: 8200 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /live, port: 8200 }
            initialDelaySeconds: 30
            periodSeconds: 30


---

# outbox-publisher-service.yaml (Health service for monitoring)
apiVersion: v1
kind: Service
metadata:
  name: outbox-publisher-health
  namespace: taskforge
spec:
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    app: outbox-publisher
  type: ClusterIP

              
